language: php
sudo: required

services:
  - mysql

before_script:
  - phpenv config-rm xdebug.ini || true
  - ./tests/LDAP/ldap_run.sh
  - composer self-update
  - rm -f composer.lock
  - composer config --unset platform
  - nvm install --lts=dubnium # update node to dubnium LTS version (node v10.x + npm v6.9.0)
  - bin/console dependencies install --composer-options="--prefer-dist --no-progress"
  - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
  - mysql -u root -e 'create database glpitest;'
  - bin/console glpi:database:install --config-dir=./tests --no-interaction --db-name=glpitest --db-user=root
  - ./tests/LDAP/ldap_fixtures.sh > /dev/null

script:
  - mysql -u root -e 'select version();'
  - composer testldap

matrix:
  include:
    - php: 7.0
      dist: xenial
      addons:
        apt:
          packages:
            - ldap-utils
            - slapd
        hosts:
          - openldap
    - php: 7.4
      dist: bionic
      addons:
        apt:
          packages:
            - ldap-utils
            - slapd
        hosts:
          - openldap
    - php: nightly
      dist: bionic
      addons:
        apt:
          packages:
            - ldap-utils
            - slapd
        hosts:
          - openldap
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm/_cacache

#exclude old branches, without tests
branches:
  except:
    - /^0\..*$/
