version: 2

shared: &shared
  steps:
    - attach_workspace:
        at: /home/circleci
    - run:
        name: Install codebase
        command: cp -a /home/circleci/codebase/. ./
    - restore_cache:
        keys:
          - composer-cache-{{ .Environment.CIRCLE_JOB }}
    - restore_cache:
        keys:
          - composer-install-{{ .Environment.CIRCLE_JOB }}-{{ checksum "composer.lock" }}
          - composer-install-{{ .Environment.CIRCLE_JOB }}
    - run:
        name: composer install
        command: |
          sed -e '/"php":/d' -i composer.json
          mv composer.lock composer.lock.bak
          composer install --optimize-autoloader --prefer-dist --no-interaction --no-progress --no-suggest
    - save_cache:
        key: composer-cache-{{ .Environment.CIRCLE_JOB }}-{{ epoch }}
        paths:
          - ./home/circleci/.composer/cache/
    - save_cache:
        key: composer-install-{{ .Environment.CIRCLE_JOB }}-{{ checksum "composer.lock.bak" }}
        paths:
          - ./vendor
    - run:
        name: PHP Parallel Lint
        command: vendor/bin/parallel-lint  --exclude files --exclude plugins --exclude vendor --exclude tools/vendor .
    - run:
        name: sensiolabs/security-checker
        command: vendor/bin/security-checker security:check
    - run:
        name: Coding standards
        command: if [[ $(php --version|grep "7\.3") ]]; then vendor/bin/phpcs -d memory_limit=512M -p -n vendor/bin/phpcs -d memory_limit=512M -p --standard=vendor/glpi-project/coding-standard/GlpiStandard/ --ignore=/vendor/,/plugins/,/files/,/lib/,/config/,/tests/config,/css/tiny_mce,/.git ./; else echo "No CS for this version"; fi
    - run:
        name: Update DB
        command: |
          mysql -h 127.0.0.1 -u root -e 'create database glpitest0723;'
          mysql -h 127.0.0.1 -u root glpitest0723 < tests/glpi-0.72.3-empty.sql
          cp tests/circleci.config_db.php tests/config_db.php
          bin/console glpi:database:update --config-dir=./tests --allow-unstable --no-interaction
          bin/console glpi:database:update --config-dir=./tests --allow-unstable --no-interaction |grep -q "No migration needed." || (echo "glpi:database:update command FAILED" && exit 1)
          bin/console glpi:migration:myisam_to_innodb --config-dir=./tests --no-interaction
          rm tests/config_db.php
    - run:
        name: Install DB
        command: |
          mysql -h 127.0.0.1 -u root -e 'create database glpitest;'
          bin/console glpi:database:install --config-dir=./tests --no-interaction --db-name=glpitest --db-host=127.0.0.1 --db-user=root
          bin/console glpi:database:update --config-dir=./tests --no-interaction |grep -q "No migration needed." || (echo "glpi:database:update command FAILED" && exit 1)
    - run:
        name: Unit tests
        command: php vendor/bin/atoum -p 'php -d memory_limit=512M' --debug --force-terminal --use-dot-report --configurations tests/telemetry.php --bootstrap-file tests/bootstrap.php --no-code-coverage -d tests/units
    - run:
        name: Database tests
        command: php vendor/bin/atoum -p 'php -d memory_limit=512M' --debug --force-terminal --use-dot-report --configurations tests/telemetry.php --bootstrap-file tests/bootstrap.php --no-code-coverage --max-children-number 1 -d tests/database
    - run:
        name: Functionnal tests
        command: php vendor/bin/atoum -p 'php -d memory_limit=512M' --debug --force-terminal --use-dot-report --configurations tests/telemetry.php --bootstrap-file tests/bootstrap.php --no-code-coverage --max-children-number 1 -d tests/functionnal
    - run:
        name: WEB tests
        command: |
          php -S localhost:8088 tests/router.php &>/dev/null &
          php vendor/bin/atoum -p 'php -d memory_limit=512M' --debug --force-terminal --use-dot-report --configurations tests/telemetry.php --bootstrap-file tests/bootstrap.php --no-code-coverage --max-children-number 1 -d tests/web
#    - run:
#        name: LDAP tests
#        command: |
#          ./tests/LDAP/ldap_run.sh
#          composer testldap

jobs:
  checkout:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout:
          path: /home/circleci/codebase
      - run: rm -rf /home/circleci/codebase/.git
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - codebase
  php_5_6_test_suite:
    <<: *shared
    docker:
      - image: glpi/circleci-env-core:php_5.6_fpm-node
      - image: circleci/mariadb:10.1
  php_7_0_test_suite:
    <<: *shared
    docker:
      - image: glpi/circleci-env-core:php_7.0_fpm-node
      - image: circleci/mariadb:10.2
  php_7_1_test_suite:
    <<: *shared
    docker:
      - image: glpi/circleci-env-core:php_7.1_fpm-node
      - image: circleci/mariadb:10.3
  php_7_2_test_suite:
    <<: *shared
    docker:
      - image: glpi/circleci-env-core:php_7.2_fpm-node
      - image: circleci/mariadb:10.3
  php_7_3_test_suite:
    <<: *shared
    docker:
      - image: glpi/circleci-env-core:php_7.3_fpm-node
      - image: circleci/mariadb:10.3
  php_latest_test_suite:
    <<: *shared
    docker:
      - image: glpi/circleci-env-core:php_latest_fpm-node
      - image: circleci/mariadb:10.3


workflows:
  version: 2
  tests_all:
    jobs:
      - checkout:
          filters:
            tags:
              only: /.*/ # required as test_suites waits for this job to be done
      - php_5_6_test_suite:
          requires:
            - checkout
          filters:
            tags:
              only: /.*/ # run also on tag creation
      - php_7_0_test_suite:
          requires:
            - checkout
          filters:
            tags:
              only: /.*/ # run also on tag creation
      - php_7_1_test_suite:
          requires:
            - checkout
          filters:
            tags:
              only: /.*/ # run also on tag creation
            branches:
              ignore: /.*/ # do not run on branch update
      - php_7_2_test_suite:
          requires:
            - checkout
          filters:
            tags:
              only: /.*/ # run also on tag creation
            branches:
              ignore: /.*/ # do not run on branch update
      - php_7_3_test_suite:
          requires:
            - checkout
          filters:
            tags:
              only: /.*/ # run also on tag creation
  scheduled_build:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
                - 9.4/bugfixes
    jobs:
      - checkout
      - php_5_6_test_suite:
          requires:
            - checkout
      - php_7_0_test_suite:
          requires:
            - checkout
      - php_7_1_test_suite:
          requires:
            - checkout
      - php_7_2_test_suite:
          requires:
            - checkout
      - php_7_3_test_suite:
          requires:
            - checkout
      - php_latest_test_suite:
          requires:
            - checkout
